### ISSUE TITLE
[1.18.1] Friends on the server cannot use the teleport

### ISSUE THREAD

**Issue by nkf-v** [ArtixAllMighty/Telepads2016#60]
I have a forge server with the current mod within a local network to play with friends. They cannot use my telepads, and adding to the whitelist does not solve the problem. Sometimes the whitelist doesn't work at all.

Minecraft 1.18.1
Forge 39.0.8

**Comment by AbsolemJackdaw** [comment]
5.0.1.0 ? 
could you describe the steps taken so i can try and recreate it in my dev environment ?

**Comment by AbsolemJackdaw** [comment]
just tested sharing in dev on a local server
![image](https://user-images.githubusercontent.com/3628535/148388305-e620ba70-b178-40e1-9171-80dfc59fbc54.png)

make sure to toggle the share button when placing pads, or have your friend shift right click an already placed telepad so the network has it's uuid bound to the location

**Comment by AbsolemJackdaw** [comment]
The whitelist isn't made to allow people to use your telepads after they are placed. 
The whitelist is made so you can register share when placing a telepad, ommiting the fact that your friends have to be on-place to right click to register a telepad. 
telepad blocks can be used by everyone. 
the network (world save data) has uuid's paired up with locations. users can go to the locations that have been registered to their uuid. 
the whitelist is only there to register a position to all uuids in yoru list + yours when placing a telepad.

this may just be a misunderstanding instead of a bug

**Comment by AbsolemJackdaw** [comment]
Due to absence of an answer and the theory posted above, I have marked this issue as resolved. 
Feel free to reopen if the issue did not get resolved
